### ISSUE TITLE
似乎没有发布 live2d-helper@2 的版本

### ISSUE THREAD

**Issue by viewweiwu** [kooritea/live2d-helper#3]
想用 3 的模型。

**Comment by kooritea** [comment]
是的还没发布2版本。。
因为还有些小功能没完善

**Comment by viewweiwu** [comment]
非常的期待(☆▽☆)

**Comment by kooritea** [comment]
dist文件夹里面的index.js如果不使用语音的话应该可以使用
配置的话还没写在readme上，可以参考下demo里面的用法，只不过有一半以上的配置现在是无效的。。

**Comment by viewweiwu** [comment]
好的，我试试！

**Comment by viewweiwu** [comment]
可以加载了！
另外想请问一下，能不能调整比例大小，我好像没有调整出来。
